version: "3.8"

services:
  mysql:
    image: mysql:9.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - test-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "1.0"
          memory: 1024M

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - test-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 256M

  mongodb_primary:
    image: mongo:7.0
    container_name: mongodb_primary
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - test-network
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb/primary:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
      - ./script/init-replica.sh:/init-replica.sh
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 512M

  mongodb_secondary:
    image: mongo:7.0
    container_name: mongodb_secondary
    networks:
      - test-network
    depends_on:
      - mongodb_primary
    volumes:
      - ./data/mongodb/secondary:/data/db
      - ./mongo-keyfile:/etc/mongo-keyfile
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 256M

  mongodb_arbiter:
    image: mongo:7.0
    container_name: mongodb_arbiter
    networks:
      - test-network
    depends_on:
      - mongodb_primary
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/etc/mongo-keyfile"]
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 128M

networks:
  test-network:
    driver: bridge
